[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "invocationeventjs"
description = "Receives a payload and returns information about it."
type = "function"
salesforce-api-version = "56.0"