[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "loggerjs"
description = "Generates an amount of log messages every number of seconds."
type = "function"
salesforce-api-version = "54.0"