[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "dataapiqueryjs"
description = "Returns accounts and its contacts by keyword."
type = "function"
salesforce-api-version = "56.0"