[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "processlargedatajs"
description = "From a large JSON payload calculates the distance between a supplied point of origin cordinate and the data, sorts it, and returns the nearest x results."
type = "function"
salesforce-api-version = "56.0"