[_]
schema-version = "0.2"

[com.salesforce]
schema-version = "0.1"
id = "orginfots"
description = "Returns the Salesforce Org information attached to the context."
type = "function"
salesforce-api-version = "56.0"